import Navbar from "@/components/home-components/navbar";
import ProtectedRoute from "@/components/security-components/protected";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { Orbitron, Rock_Salt, Ubuntu } from "next/font/google";
import "../globals.css";

const rockSalt = Rock_Salt({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-rock-salt",
});

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-orbitron",
});

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-ubuntu",
});

export const metadata: Metadata = {
  title: "Pixel Shield",
  description: "Generated by create next app",
};

export default function RoutesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProtectedRoute>
      <Navbar />
      {children}
      <Toaster />
    </ProtectedRoute>
  );
}
