export const starWarsQuotes = [
    "Do or do not, there is no try.",
    "I’ve got a bad feeling about this.",
    "The Force will be with you. Always.",
    "In my experience, there is no such thing as luck.",
    "Never tell me the odds!",
    "I find your lack of faith disturbing.",
    "It's a trap!",
    "I am your father.",
    "The Force is strong with this one.",
    "I've been waiting for you, Obi-Wan.",
    "Your focus determines your reality.",
    "The ability to speak does not make you intelligent.",
    "When 900 years old you reach, look as good you will not.",
    "Fear is the path to the dark side. Fear leads to anger; anger leads to hate; hate leads to suffering.",
    "So this is how liberty dies…with thunderous applause.",
    "Power! Unlimited power!",
    "I am one with the Force, and the Force is with me.",
    "Hope is like the sun. If you only believe it when you see it, you’ll never make it through the night.",
    "Rebellions are built on hope.",
    "I’ll never turn to the dark side. You’ve failed, your highness. I am a Jedi, like my father before me.",
    "Let the Wookiee win.",
    "I’ve been looking forward to this.",
    "Be mindful of your thoughts, Anakin. They betray you.",
    "I’m just a simple man trying to make my way in the universe.",
    "So this is how liberty dies…with thunderous applause.",
    "He’s no good to me dead.",
    "I’ll see you again. I promise.",
    "Just for once, let me look on you with my own eyes.",
    "I will not let this Republic that has stood for a thousand years be split in two. My negotiations will not fail.",
    "Chewie, we’re home."
  ];
  