import Navbar from "@/components/home-components/navbar";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Rock_Salt, Ubuntu } from 'next/font/google';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  display: "auto",
  weight: "100 900",
});

const rockSalt = Rock_Salt({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-rock-salt',
});

const ubuntu = Ubuntu({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-ubuntu',
});

export const metadata: Metadata = {
  title: "Pixel Shield",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.variable} ${rockSalt.variable} antialiased`}
      >
          <Navbar/>
          {children}
      </body>
    </html>
  );
}
